# default snakemake parameters for this profile
restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 5
cores: 3
latency-wait: 60
use-conda: True
rerun-incomplete: True
jobs: 5
scheduler: greedy
shadow-prefix: /scratch/midway2/bjf79
